/*1*/Sprint2.restaurantes.find({});
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.
/**/Sprint2.restaurantes.